Algoritmo "nomidade"

Var
nome1, nome2:caractere
idade1, idade2, mult:real


Inicio
escreval("Insira o primeiro nome")
leia(nome1)
escreval("Insira o segundo nome")
leia(nome2)
escreval("Insira a primeira idade")
leia(idade1)
escreval("Insira a segunda idade")
leia(idade2)

mult <- (idade1 * idade2);

escreval("A multiplicacao das idades de ",nome1," e ",nome2," e igual a ",mult)


Fimalgoritmo