Algoritmo "numeros"

Var
num, qua, tri, raiz, soma:real

Inicio
escreval("insira o numero desejado")
leia(num)
qua <- num * num;
tri <- num * num * num;
raiz <- raizq(num);
soma <- (raizq(num) + tri);

escreval("O numero inserido e ", num,", o quadrado do numero equivale a ",qua,", o cubo    equivale a ", tri,", a raiz quadrada equivale a ", raiz," e a soma equivale a ", soma)


Fimalgoritmo